export const API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL
export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL
export const STRIPE_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY